#!/usr/bin/env python3
"""Export the contract ABI and method selectors to a committed file.

Two reasons this is not done by hand or by copy-paste:

1. Selectors. Hand-typing them failed once already: two of three were wrong (CANON() is
   c54d5827, latestCommittedBlock() is d2ec073f). Anything that reads them must derive them
   from the compilation, not from memory.

2. One source. A consumer keeping its own copy of the ABI is a second transcription of a fact
   that already exists, and second transcriptions drift silently. The file this writes is
   checked into git so the consumer can `git pull` it, and CI regenerates it and fails if the
   result differs -- so the committed copy cannot fall behind the contract.

Usage:
    python tools/export_abi.py                 # write abis/EvidenceLedger.json
    python tools/export_abi.py --check         # fail if the file is not what a build produces
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

TARGET = "src/EvidenceLedger.sol:EvidenceLedger"
OUT = Path("abis/EvidenceLedger.json")


def forge(args: list[str]) -> str:
    proc = subprocess.run(["forge", *args], capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"forge {' '.join(args)} failed:\n{proc.stderr or proc.stdout}")
    return proc.stdout


def build(root: Path) -> dict:
    abi = json.loads(forge(["inspect", TARGET, "abi", "--json"]))
    identifiers = json.loads(forge(["inspect", TARGET, "methodIdentifiers", "--json"]))
    return {
        "contract": "EvidenceLedger",
        "source": "src/EvidenceLedger.sol",
        "note": "Generated by tools/export_abi.py. Do not edit; CI fails if this drifts.",
        "abi": abi,
        "methodIdentifiers": identifiers,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    root = args.root.resolve()
    data = build(root)
    body = json.dumps(data, indent=2, sort_keys=False) + "\n"
    target = root / OUT

    if args.check:
        if not target.is_file():
            print(f"{OUT} is missing; run tools/export_abi.py")
            return 1
        if target.read_text(encoding="utf-8") != body:
            print(f"{OUT} differs from a fresh build. The committed ABI has drifted from the")
            print("contract. Run tools/export_abi.py and commit the result.")
            return 1
        print(f"{OUT} matches a fresh build")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    print(f"  {len(data['abi'])} ABI entries, {len(data['methodIdentifiers'])} selectors")
    for sig, sel in sorted(data["methodIdentifiers"].items()):
        print(f"    {sel}  {sig}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
